### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by nirnaeth-arnoediad**
1) "visitor-as": "^0.6.0" conflicts with assemblyscript 0.19+ when we run npm install. We should update it to 0.8.0
2) update assemblyscript to 0.19.23
3) update massa-sc-std to 3.2.2

### CODE REVIEW

**Comment by gregLibert** [comment]
hey @nirnaeth-arnoediad thank you for this ! I just tagged a new version of https://github.com/massalabs/massa-sc-std, v4.0.0, that makes the function signatures cleaner.

Can you update the package.json to match this new version ?

**Comment by nirnaeth-arnoediad** [comment]
> hey @nirnaeth-arnoediad thank you for this ! I just tagged a new version of https://github.com/massalabs/massa-sc-std, v4.0.0, that makes the function signatures cleaner.
> 
> Can you update the package.json to match this new version ?

Hey @gregLibert. I have just updated massa-sc-std to v4.0.0 on package.json

**Comment by nirnaeth-arnoediad** [comment]
btw, I made some commits to solve issue #22 but my commits shown here in this PR. How can I make them apart

**Comment by gregLibert** [comment]
The last version of massa-sc-std is 4.0.1.

Furthermore this branch is not working. I did:
- git clone https://github.com/nirnaeth-arnoediad/massa-sc-template
- cd massa-sc-template/
-  npm install
- yarn run build

And it gave me the following:
```shell
$ massa-sc-scripts build-sc && massa-sc-scripts build-sc src/main.ts build/main.wasm
Running asc src/smart-contract.ts --transform mscl-as-transformer --transform json-as/transform --target release --exportRuntime --runtime stub --binaryFile build/smart-contract.wasm...
Running asc src/main.ts --transform mscl-as-transformer --transform json-as/transform --target release --exportRuntime --runtime stub --binaryFile build/main.wasm...
ERROR TS2305: Module '~lib/massa-sc-std' has no exported member 'create_sc'.

 import { create_sc, include_base64, generate_event, call, Context } from "massa-sc-std";
          ~~~~~~~~~
 in src/main.ts(10,10)

ERROR TS2305: Module '~lib/massa-sc-std' has no exported member 'include_base64'.

 import { create_sc, include_base64, generate_event, call, Context } from "massa-sc-std";
                     ~~~~~~~~~~~~~~
 in src/main.ts(10,21)

ERROR TS2305: Module '~lib/massa-sc-std' has no exported member 'generate_event'.

 import { create_sc, include_base64, generate_event, call, Context } from "massa-sc-std";
                                     ~~~~~~~~~~~~~~
 in src/main.ts(10,37)

WARNING AS226: Expression resolves to unusual type 'usize'.

 const unknownNull = unknown.wrap(null)
                                  ~~~~
 in ~lib/json-as/index.ts(54,34)

WARNING AS226: Expression resolves to unusual type 'usize'.

         if (data instanceof usize && data === null) {
                                               ~~~~
 in ~lib/json-as/unknown.ts(25,47)

ERROR TS2304: Cannot find name 'create_sc'.

     let addr = create_sc(bytes);
                ~~~~~~~~~
 in src/main.ts(15,16)

ERROR TS2304: Cannot find name 'generate_event'.

     generate_event("Address = " + addr);
     ~~~~~~~~~~~~~~
 in src/main.ts(16,5)

ERROR TS2304: Cannot find name 'generate_event'.

     generate_event(call(addr, "helloworld", "World", 0));
     ~~~~~~~~~~~~~~
 in src/main.ts(18,5)

ERROR TS2304: Cannot find name 'generate_event'.

     generate_event(`${Context.get_call_stack()[0]}`)
     ~~~~~~~~~~~~~~
 in src/main.ts(19,5)

FAILURE 7 compile error(s)

```

**Review by gregLibert — CHANGES_REQUESTED** [review]
Not working

**Comment by qdrn** [comment]
Thanks @nirnaeth-arnoediad for updating the package.json. We made several changes in the meantime. I've updated the template in #30. Closing this one as a result.

**Pull request closed without merging**
